version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: parfum
      POSTGRES_PASSWORD: parfum
      POSTGRES_DB: parfum
    ports:
      - "5432:5432"
    volumes:
      - parfum_db:/var/lib/postgresql/data
volumes:
  parfum_db:
